--- #YAML:1.0
name:               Hash-MostUtils
version:            1.01
abstract:           Pairwise list manipulators
author:
    - Belden Lyman <belden@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://github.com/belden/perl-hash-mostutils/issues
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
